name: 'tenderd-build-push-images-hub'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tenderd-build-push-images-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract branch name
        id: extract_version
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          # Handle PRs and replace slashes
          if [[ $GITHUB_REF == refs/pull/* ]]; then
            BRANCH_NAME="pr-${GITHUB_REF##*/}"
          fi
          # Sanitize branch name for Docker tags
          BRANCH_NAME=$(echo $BRANCH_NAME | sed 's/[^a-zA-Z0-9._-]/_/g')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Install dependencies for frontend service
        run: |
          cd ./frontend-svc
          npm install

      - name: Run tests for frontend service
        run: |
          cd ./frontend-svc
          npm test

      - name: Install dependencies for order service
        run: |
          cd ./order-svc
          npm install

      - name: Run tests for order service
        run: |
          cd ./order-svc
          npm test

      - name: Install dependencies for user service
        run: |
          cd ./user-svc
          npm install

      - name: Run tests for user service
        run: |
          cd ./user-svc
          npm test 

      - name: Build and push Docker images
        if: success()
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/tenderd-devops-frontend-svc:v2 --push ./frontend-svc
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/tenderd-devops-order-svc:v2 --push ./order-svc
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/tenderd-devops-user-svc:v2 --push ./user-svc
